/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foropractica.Ventanas;

import foropractica.Clases.Forero.Administrador;
import foropractica.Ventanas.Aviso.ventanaAvisoNoSancionados;
import foropractica.Clases.Forero.Moderador;
import foropractica.Comparadores.NumSancionesModerador;
import javax.swing.DefaultListModel;
import foropractica.Paneles.*;
import foropractica.Ventanas.Aviso.ventanaAvisoNoForeros;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.TreeSet;

/** 
* Clase ventanaListaModeradores, muestra los moderadores actuales
*
* @author David Correas, Alejandro Quesada, José Zamora
* @version 4/1/2018
*/
public class ventanaListaModeradores extends javax.swing.JFrame {

    /**
     * Creates new form ventanaListaModeradores
     */
    static DefaultListModel dlMod;
    static Moderador moderador_;
    
    public ventanaListaModeradores() {
        dlMod = new DefaultListModel();
        initComponents();     
        setLocationRelativeTo(null);
        refrescarModeradores();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaMod = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(80, 89, 92));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 155, 155));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foropractica/Recursos/Foro/moderad_16px.png"))); // NOI18N
        jLabel1.setText("Lista de Moderadores:");

        ListaMod.setModel(dlMod);
        ListaMod.setCellRenderer(new panelModeradores());
        ListaMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaModMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaMod);

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 216, 216));
        jLabel2.setText("Nick:");

        jLabel3.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 216, 216));
        jLabel3.setText("Numero sancionados:");

        jLabel4.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 216, 216));
        jLabel4.setText("Numero sancionados historico:");

        jToggleButton1.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButton1.setText("Ordenar por numero de sanciones");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Pulsar para ver sancionados y levantar sanciones.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jToggleButton1)
                            .addGap(74, 74, 74)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel2)
                .addGap(261, 261, 261)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jButton1)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        dlMod.clear();
        if (jToggleButton1.isSelected()){
            if(ventanaPrincipal.foro_.getModeradoresOrdenado().isEmpty() && ventanaPrincipal.foro_.getAdministradores().isEmpty()){
                new ventanaAvisoNoForeros(this, true).setVisible(true);
                this.dispose();
                
            }else{

                ArrayList<Moderador> modOrdRev = new ArrayList();
                modOrdRev.clear();
                modOrdRev.addAll(ventanaPrincipal.foro_.getModeradores());
                modOrdRev.addAll(ventanaPrincipal.foro_.getAdministradores());
                modOrdRev.sort(new NumSancionesModerador());
                
                Collections.reverse(modOrdRev);
                for (Moderador m : modOrdRev){
                    dlMod.addElement(m);
                }
            }
        }else
        {
            refrescarModeradores();
        }
                
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ListaModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaModMouseClicked
        moderador_ = ListaMod.getSelectedValue();
        if(!moderador_.getForerosSancionados().isEmpty() && !moderador_.getForerosSancionadosHist().isEmpty())
        {
            this.dispose();
            new ventanaModerador(moderador_).setVisible(true);
        }
        else
        {
            new ventanaAvisoNoSancionados(this,true).setVisible(true);
        }
    }//GEN-LAST:event_ListaModMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaListaModeradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaListaModeradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaListaModeradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaListaModeradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JList<Moderador> ListaMod;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    private void refrescarModeradores() {
        dlMod.clear();
        if(ventanaPrincipal.foro_.getModeradores().isEmpty() && ventanaPrincipal.foro_.getAdministradores().isEmpty())
        {
            new ventanaAvisoNoForeros(this, true).setVisible(true);
            this.dispose();
            
        }else{
            ArrayList<Moderador> listr = new ArrayList();
            listr.clear();
            listr.addAll(ventanaPrincipal.foro_.getModeradores());
            listr.addAll(ventanaPrincipal.foro_.getAdministradores());
            Collections.sort(listr);
            
            
            for (Moderador m : listr)
            {
                dlMod.addElement(m);
            }
        }
    }
}
