/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foropractica.Ventanas;

import foropractica.Clases.Forero.Administrador;
import foropractica.Clases.Forero.Forero;
import foropractica.Clases.Forero.Moderador;
import foropractica.Clases.Foro.Foro;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/** 
* Clase ventanaForero, muestra toda la informacion sobre un forero
*
* @author David Correas, Alejandro Quesada, José Zamora
* @version 4/1/2018
*/
public class ventanaForero extends javax.swing.JFrame {
    
    static Forero forero_;

    /**
     * Creates new form ventanaForero
     * @param fore_
     */
    public ventanaForero(Forero fore_) {
        initComponents();
        setLocationRelativeTo(null);
        forero_ = fore_;
        labelError.setVisible(false);
        sancionar.setVisible(false);
        levantarSancion.setVisible(false);
        ficheroCreado.setVisible(false);
        labelNick.setText(forero_.getNick());
        if(!forero_.getNombre().isEmpty())
        {
            labelNombre.setText(forero_.getNombre());
        }else{
            labelNombre.setText("<unknown>");
        }
        
        if(!forero_.getApellidos().isEmpty())
        {
            labelApellidos.setText(forero_.getApellidos());
        }else{
            labelApellidos.setText("<unknown>");
        }
        
        if(forero_.CategoriaMasFrecuente() != null)
        {
            labelCategoriaFrecuente.setText(forero_.CategoriaMasFrecuente().getNombre());
        }else{
            labelCategoriaFrecuente.setText("<none>");
        }
        
        labelNumeroMensajes.setText(Integer.toString(forero_.getNumMensajes()));
        
        labelRol.setText(ventanaPrincipal.foro_.dameRol(forero_));
        
        if(!forero_.getTelefono().isEmpty())
        {
            labelTelefono.setText(forero_.getTelefono());
        }else{
            labelTelefono.setText("<unknown>");
        }
        
        if(forero_.getSancionado())
        {
            labelSancionado.setText("Si");
        }else{
            labelSancionado.setText("No");
        }
        
        labelVecesSancionado.setText(Integer.toString(forero_.getVecesSancionado()));
        
        if("Administrador".equals(ventanaPrincipal.foro_.dameRol(ventanaPrincipal.user)))
        {
            if("Administrador".equals(ventanaPrincipal.foro_.dameRol(forero_)))
            {
                ascenderModeradorBut.setVisible(false);
                degradarModeradorBut.setVisible(false);
            }else if("Moderador".equals(ventanaPrincipal.foro_.dameRol(forero_)))
            {
                ascenderModeradorBut.setVisible(true);
                degradarModeradorBut.setVisible(true);
            }else{
                ascenderModeradorBut.setVisible(true);
                degradarModeradorBut.setVisible(false);
                if (forero_.getSancionado())
                    levantarSancion.setVisible(true);
                else
                    sancionar.setVisible(true);
            }
        }
        else if ("Moderador".equals(ventanaPrincipal.foro_.dameRol(ventanaPrincipal.user)))
        {
            if("Administrador".equals(ventanaPrincipal.foro_.dameRol(forero_)))
            {
                ascenderModeradorBut.setVisible(false);
                degradarModeradorBut.setVisible(false);
            }else if("Moderador".equals(ventanaPrincipal.foro_.dameRol(forero_)))
            {
                ascenderModeradorBut.setVisible(false);
                degradarModeradorBut.setVisible(false);
                sancionar.setVisible(false);
                levantarSancion.setVisible(false);
            }else{
                ascenderModeradorBut.setVisible(false);
                degradarModeradorBut.setVisible(false);
                if (forero_.getSancionado())
                    levantarSancion.setVisible(true);
                else
                    sancionar.setVisible(true);
            }

        }else{
            ascenderModeradorBut.setVisible(false);
            degradarModeradorBut.setVisible(false);
            jTextFieldFichero.setVisible(false);
            jButtonCrearFichero.setVisible(false);
            jLabel9.setVisible(false);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelApellidos = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelCategoriaFrecuente = new javax.swing.JLabel();
        labelSancionado = new javax.swing.JLabel();
        labelVecesSancionado = new javax.swing.JLabel();
        labelNick = new javax.swing.JLabel();
        labelNumeroMensajes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelRol = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ascenderModeradorBut = new javax.swing.JButton();
        degradarModeradorBut = new javax.swing.JButton();
        jTextFieldFichero = new javax.swing.JTextField();
        jButtonCrearFichero = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        labelError = new javax.swing.JLabel();
        sancionar = new javax.swing.JButton();
        levantarSancion = new javax.swing.JButton();
        ficheroCreado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(80, 89, 92));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelNombre.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setText("jLabel1");

        labelApellidos.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        labelApellidos.setForeground(new java.awt.Color(255, 255, 255));
        labelApellidos.setText("jLabel2");

        labelTelefono.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        labelTelefono.setForeground(new java.awt.Color(255, 255, 255));
        labelTelefono.setText("jLabel3");

        labelCategoriaFrecuente.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        labelCategoriaFrecuente.setForeground(new java.awt.Color(255, 255, 255));
        labelCategoriaFrecuente.setText("jLabel4");

        labelSancionado.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        labelSancionado.setForeground(new java.awt.Color(255, 255, 255));
        labelSancionado.setText("jLabel5");

        labelVecesSancionado.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        labelVecesSancionado.setForeground(new java.awt.Color(255, 255, 255));
        labelVecesSancionado.setText("jLabel6");

        labelNick.setBackground(new java.awt.Color(233, 155, 155));
        labelNick.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        labelNick.setForeground(new java.awt.Color(48, 41, 57));
        labelNick.setText("jLabel8");

        labelNumeroMensajes.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        labelNumeroMensajes.setForeground(new java.awt.Color(255, 255, 255));
        labelNumeroMensajes.setText("jLabel7");

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 216, 216));
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 216, 216));
        jLabel2.setText("Apellidos:");

        jLabel3.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 216, 216));
        jLabel3.setText("Telefono:");

        jLabel4.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 216, 216));
        jLabel4.setText("Categoria más frecuente:");

        jLabel5.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 216, 216));
        jLabel5.setText("Numero de mensajes:");

        jLabel6.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 216, 216));
        jLabel6.setText("Sancionado:");

        jLabel7.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 216, 216));
        jLabel7.setText("Veces Sancionado:");

        jLabel8.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 216, 216));
        jLabel8.setText("Rol:");

        labelRol.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        labelRol.setForeground(new java.awt.Color(255, 255, 255));
        labelRol.setText("jLabel9");

        jButton1.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ascenderModeradorBut.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        ascenderModeradorBut.setText("Ascender a Moderador");
        ascenderModeradorBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ascenderModeradorButActionPerformed(evt);
            }
        });

        degradarModeradorBut.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        degradarModeradorBut.setText("Degradar a Forero");
        degradarModeradorBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degradarModeradorButActionPerformed(evt);
            }
        });

        jTextFieldFichero.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldFichero.setFont(new java.awt.Font("Lucida Console", 0, 11)); // NOI18N
        jTextFieldFichero.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldFichero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButtonCrearFichero.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        jButtonCrearFichero.setText("Crear TXT");
        jButtonCrearFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearFicheroActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText(".txt");

        labelError.setForeground(new java.awt.Color(255, 102, 102));
        labelError.setText("No puedes crear un fichero sin nombre ...");

        sancionar.setBackground(new java.awt.Color(255, 102, 102));
        sancionar.setForeground(new java.awt.Color(255, 255, 255));
        sancionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foropractica/Recursos/Foro/Unavailable_16px.png"))); // NOI18N
        sancionar.setToolTipText("Sancionar");
        sancionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sancionarActionPerformed(evt);
            }
        });

        levantarSancion.setBackground(new java.awt.Color(153, 255, 153));
        levantarSancion.setForeground(new java.awt.Color(51, 51, 51));
        levantarSancion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foropractica/Recursos/Foro/levantar_16px.png"))); // NOI18N
        levantarSancion.setToolTipText("Levantar Sanción");
        levantarSancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levantarSancionActionPerformed(evt);
            }
        });

        ficheroCreado.setForeground(new java.awt.Color(153, 255, 153));
        ficheroCreado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ficheroCreado.setText("El fichero se ha creado correctamente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jButtonCrearFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(degradarModeradorBut, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ascenderModeradorBut)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ficheroCreado, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(labelError)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelNick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(sancionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(levantarSancion)
                                .addGap(86, 86, 86))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelApellidos)
                                    .addComponent(labelNombre)
                                    .addComponent(labelTelefono)
                                    .addComponent(labelCategoriaFrecuente)
                                    .addComponent(labelNumeroMensajes)
                                    .addComponent(labelSancionado)
                                    .addComponent(labelVecesSancionado)
                                    .addComponent(labelRol))
                                .addGap(84, 84, 84)))))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(labelNick))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sancionar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(levantarSancion, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelApellidos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelTelefono))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelCategoriaFrecuente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelNumeroMensajes))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelSancionado))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelVecesSancionado))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelRol))
                .addGap(30, 30, 30)
                .addComponent(degradarModeradorBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ascenderModeradorBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrearFichero)
                    .addComponent(jTextFieldFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ficheroCreado)
                    .addComponent(labelError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ascenderModeradorButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ascenderModeradorButActionPerformed
        ventanaPrincipal.foro_.nombrarModerador(forero_);
        labelRol.setText(ventanaPrincipal.foro_.dameRol(forero_));
        
        if("Administrador".equals(ventanaPrincipal.foro_.dameRol(ventanaPrincipal.user)))
        {
            degradarModeradorBut.setVisible(true);
            ascenderModeradorBut.setVisible(false);
            sancionar.setVisible(false);
            levantarSancion.setVisible(false);
        }
        else
        {
            degradarModeradorBut.setVisible(false);
            ascenderModeradorBut.setVisible(false);
            sancionar.setVisible(false);
            levantarSancion.setVisible(false);
        }
        
        try {
            ventanaPrincipal.foro_.actualizarEnMemoria();
        } catch (IOException ex) {
            Logger.getLogger(ventanaForero.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ascenderModeradorButActionPerformed

    private void degradarModeradorButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degradarModeradorButActionPerformed
        ventanaPrincipal.foro_.destituirModerador(forero_);
        labelRol.setText(ventanaPrincipal.foro_.dameRol(forero_));
        
        if("Administrador".equals(ventanaPrincipal.foro_.dameRol(ventanaPrincipal.user)))
        {
            degradarModeradorBut.setVisible(false);
            ascenderModeradorBut.setVisible(true);
            if (forero_.getSancionado())
                    levantarSancion.setVisible(true);
            else
                    sancionar.setVisible(true);
        }
        else
        {
            degradarModeradorBut.setVisible(false);
            ascenderModeradorBut.setVisible(true);
            if (forero_.getSancionado())
                    levantarSancion.setVisible(true);
            else
                    sancionar.setVisible(true);
        }
        
        try {
            ventanaPrincipal.foro_.actualizarEnMemoria();
        } catch (IOException ex) {
            Logger.getLogger(ventanaForero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_degradarModeradorButActionPerformed

    private void jButtonCrearFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearFicheroActionPerformed
        // TODO add your handling code here:
        
        ficheroCreado.setVisible(false);
        if (jTextFieldFichero.getText().equals(""))
        {
            labelError.setVisible(true);
            ficheroCreado.setVisible(false);
        }
        else
        {
            ficheroCreado.setVisible(true);
            forero_.listaMensjaesTXT(jTextFieldFichero.getText());
            
        }
        
    }//GEN-LAST:event_jButtonCrearFicheroActionPerformed

    private void sancionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sancionarActionPerformed
        // TODO add your handling code here:
        if ("Moderador".equals(ventanaPrincipal.foro_.dameRol(ventanaPrincipal.user)))
        {
            Moderador m = ventanaPrincipal.foro_.obtenerModerador(ventanaPrincipal.user.getNick());
            m.sancionar(forero_);
            ventanaListaForeros.refrescarForeros();
        }
        else
        {
            Administrador a = ventanaPrincipal.foro_.obtenerAdministrador(ventanaPrincipal.user.getNick());
            a.sancionar(forero_);
            ventanaListaForeros.refrescarForeros();
        }
           
        
        labelVecesSancionado.setText(Integer.toString(forero_.getVecesSancionado())); 
        if(forero_.getSancionado())
        {
            labelSancionado.setText("Si");
        }
        else
        {
            labelSancionado.setText("No");
        }
        
        sancionar.setVisible(false);
        levantarSancion.setVisible(true);
        
        try {
            ventanaPrincipal.foro_.actualizarEnMemoria();
        } catch (IOException ex) {
            Logger.getLogger(ventanaForero.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_sancionarActionPerformed

    private void levantarSancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levantarSancionActionPerformed
        // TODO add your handling code here:
        if ("Moderador".equals(ventanaPrincipal.foro_.dameRol(ventanaPrincipal.user)))
        {
            Moderador m = ventanaPrincipal.foro_.obtenerModerador(ventanaPrincipal.user.getNick());
            m.levantarSancion(forero_);
            ventanaListaForeros.refrescarForeros();
        }
        else
        {
            Administrador a = ventanaPrincipal.foro_.obtenerAdministrador(ventanaPrincipal.user.getNick());
            a.levantarSancion(forero_);
            ventanaListaForeros.refrescarForeros();
        }
        
        labelVecesSancionado.setText(Integer.toString(forero_.getVecesSancionado()));
        
        if(forero_.getSancionado())
        {
            labelSancionado.setText("Si");
        }else{
            labelSancionado.setText("No");
        }
        
        sancionar.setVisible(true);
        levantarSancion.setVisible(false);
        
        try {
            ventanaPrincipal.foro_.actualizarEnMemoria();
        } catch (IOException ex) {
            Logger.getLogger(ventanaForero.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_levantarSancionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaForero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaForero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaForero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaForero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ascenderModeradorBut;
    private javax.swing.JButton degradarModeradorBut;
    private javax.swing.JLabel ficheroCreado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCrearFichero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldFichero;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelCategoriaFrecuente;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelNick;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNumeroMensajes;
    private javax.swing.JLabel labelRol;
    private javax.swing.JLabel labelSancionado;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelVecesSancionado;
    private javax.swing.JButton levantarSancion;
    private javax.swing.JButton sancionar;
    // End of variables declaration//GEN-END:variables
}
