/*
 * Author: Alejandro Quesada Mendo.
 * Doble Grado Ing. infórmatica e Ing. de computadores
 * URJC
 */
package foropractica.Ventanas;

import foropractica.Clases.Foro.Hilo;
import foropractica.Clases.Foro.Mensaje;
import foropractica.Paneles.*;
import foropractica.Ventanas.Aviso.ventanaAvisoNoBorrarHilo;

import javax.swing.DefaultListModel;

/** 
* Clase ventanaMensaje, permite publicar un mensaje en un hilo o borrar el hilo
*
* @author David Correas, Alejandro Quesada, José Zamora
* @version 4/1/2018
*/
public class ventanaMensaje extends javax.swing.JFrame {

    /**
     * Creates new form ventanaMensaje
     */
    static Hilo hilo_;
    static DefaultListModel listMsg = new DefaultListModel();

    static void refrescarMensajes() {
        
        listMsg.clear();

        for(Mensaje m : hilo_.getStack()){
            listMsg.addElement(m);
        }
        
    }
    public ventanaMensaje( Hilo hilo_) {
        initComponents();
        this.setLocationRelativeTo(null);
        ventanaMensaje.hilo_ = hilo_;

        //Integer i = ventanaPrincipal.user.numMensajes();

        refrescarMensajes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMensajes = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnBorrarHilo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(80, 89, 92));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setForeground(new java.awt.Color(80, 89, 92));

        listaMensajes.setModel(listMsg);
        listaMensajes.setCellRenderer(new panelMensajes(hilo_));
        jScrollPane1.setViewportView(listaMensajes);

        jButton1.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Publicar Nuevo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnBorrarHilo.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        btnBorrarHilo.setForeground(new java.awt.Color(0, 0, 0));
        btnBorrarHilo.setText("Borrar Hilo");
        btnBorrarHilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarHiloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBorrarHilo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1067, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(btnBorrarHilo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new CrearMensaje().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBorrarHiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarHiloActionPerformed
        
        if(ventanaPrincipal.foro_.dameRol(ventanaPrincipal.user).equals("Administrador")){
            ventanaPrincipal.categoria_.eliminarHilo(hilo_);
            this.dispose();
            ventanaPrincipal.refrescarHilos();
            ventanaPrincipal.refrescarCategorias();
            ventanaPrincipal.refrescarNumero();
            ventanaPrincipal.lblRuta.setText("Estás en la Categoría: "+ ventanaPrincipal.categoria_.getNombre());
        }else{
            listaMensajes.clearSelection();
            if(ventanaPrincipal.hilo_!= null){
                if(ventanaPrincipal.hilo_.getNumMensajes() == 1 && hilo_.getAutor().equals(ventanaPrincipal.user.getNick())){
                    ventanaPrincipal.categoria_.eliminarHilo(hilo_);
                    this.dispose();
                    ventanaPrincipal.refrescarHilos();
                    ventanaPrincipal.refrescarCategorias();
                    ventanaPrincipal.refrescarNumero();
                }else{
                    new ventanaAvisoNoBorrarHilo(this, true).setVisible(true);
                }
            }
        }
        
    }//GEN-LAST:event_btnBorrarHiloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaMensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaMensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaMensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaMensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaMensaje(ventanaPrincipal.hilo_).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarHilo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    static javax.swing.JList<Mensaje> listaMensajes;
    // End of variables declaration//GEN-END:variables
}
