/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package foropractica.Paneles;

import foropractica.Clases.Forero.Forero;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/** 
* Clase panelForerosSancionados, mustra el numero de veces que ha sido 
* sancionado un forero en particular en la interfaz gráfica
*
* @author David Correas, Alejandro Quesada, José Zamora
* @version 4/1/2018
*/

public class panelForerosSancionados extends javax.swing.JPanel implements ListCellRenderer{

    /** Creates new form panelForerosSancionados */
    public panelForerosSancionados() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNick = new javax.swing.JLabel();
        labelNumSancionado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 155, 155));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setForeground(new java.awt.Color(233, 155, 155));
        setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        labelNick.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        labelNick.setForeground(new java.awt.Color(48, 41, 57));
        labelNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNick.setText("jLabel1");
        add(labelNick);

        labelNumSancionado.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        labelNumSancionado.setForeground(new java.awt.Color(48, 41, 57));
        labelNumSancionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumSancionado.setText("jLabel2");
        add(labelNumSancionado);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelNick;
    private javax.swing.JLabel labelNumSancionado;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        
        Forero forero = (Forero) value;
        labelNick.setText(forero.getNick());
        labelNumSancionado.setText(Integer.toString(forero.getVecesSancionado()));
        
        return this;
    }

}
