
package foropractica.Paneles;

import foropractica.Clases.Foro.Categoria;
import foropractica.Clases.Foro.Hilo;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/** 
* Clase panelHilos, muestra la lista de hilos que hay en cada categoria
*
* @author David Correas, Alejandro Quesada, José Zamora
* @version 4/1/2018
*/

public class panelHilos extends javax.swing.JPanel implements ListCellRenderer{
    
    Categoria categoria_;
    public panelHilos( Categoria categoria_) {
        initComponents();
        this.categoria_ = categoria_;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNombreCat = new javax.swing.JLabel();
        labelNumHilos = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 20);
        flowLayout1.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout1);

        labelNombreCat.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        labelNombreCat.setForeground(new java.awt.Color(48, 41, 57));
        labelNombreCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foropractica/Recursos/Foro/Hilo_16px.png"))); // NOI18N
        labelNombreCat.setText("[nombre del hilo]");
        labelNombreCat.setToolTipText("");
        jPanel1.add(labelNombreCat);

        labelNumHilos.setForeground(new java.awt.Color(233, 155, 155));
        labelNumHilos.setText("[numMensajes]");
        jPanel1.add(labelNumHilos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelNombreCat;
    private javax.swing.JLabel labelNumHilos;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList jlist, Object e, int i, boolean isSelected, boolean cellHasFocus) {
        Hilo h = (Hilo) e;
        labelNombreCat.setText(h.getTitulo());
        Integer integer = h.getNumMensajes();
        labelNumHilos.setText(integer.toString() + " Mensajes");
        
        if(isSelected){
          jPanel1.setBackground(Color.DARK_GRAY);
          jPanel1.setForeground(Color.WHITE);
          labelNombreCat.setForeground(Color.WHITE);
          labelNumHilos.setForeground(Color.WHITE);
        }else{
          jPanel1.setBackground(Color.WHITE);
          jPanel1.setForeground(Color.BLACK);
          labelNombreCat.setForeground(Color.BLACK);
          labelNumHilos.setForeground(Color.BLACK);
        }
        
        if(cellHasFocus){
            jPanel1.setBackground(Color.LIGHT_GRAY);
            jPanel1.setForeground(Color.WHITE);
            labelNombreCat.setForeground(Color.BLACK);
            labelNumHilos.setForeground(Color.BLACK);
        }else{
            jPanel1.setBackground(Color.WHITE);
            jPanel1.setForeground(Color.BLACK);
            labelNombreCat.setForeground(Color.BLACK);
            labelNumHilos.setForeground(Color.BLACK);
        }
        
        
        return this;
    }
}
